[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.module]
source = 'nativefs.lua'
before = 'main.lua'
name = 'nativefs'

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = ["Core/Main.lua"]

# [[patches]]
# [patches.pattern]
# target = "functions/UI_definitions.lua"
# pattern = """G.F_DAILIES and {n=G.UIT.R, config={align = "cm", padding = 0.1, r = 0.1 ,colour = G.C.BLACK}, nodes={"""
# position = "before"
# payload = """
# {n=G.UIT.R, config={align = "cm", padding = 0.1, r = 0.1 ,colour = G.C.BLACK}, nodes={Challenger.challenger_overview}},
# """
# match_indent = true
# overwrite = false
